### ISSUE TITLE
How to add PC playback audio?

### ISSUE THREAD

**Issue by pejman86** [baSSiLL/SharpAvi#11]
Hi,

Do you know how we can add playback audio to the captured AVI in addition to mic audio?

**Comment by baSSiLL** [comment]
Hi
I have not ever had a need to do this myself, so cannot provide you with readymade solution. AFAIK you can use WASAPI loopback capture in NAudio for that purpose. Check out this tutorial or google for others:
http://www.blakepell.com/2013-07-26-naudio-loopback-record-what-you-hear-through-the-speaker
