### ISSUE TITLE
Recording video and audio at the same time.

### ISSUE THREAD

**Issue by AndersBillLinden** [baSSiLL/SharpAvi#12]
Thanks for a good lib! Questions: Should I use two different threads for video and audio? Is it even possible? In the code example, video and audio streams are written after each other in a loop, but the async version of the WriteFrame methods were not used. Why not? If I would have a loop using async writing of the video and then async writing of the audio, would that either prevent audio or video to record at optimal speed? How do I select the audio input source?

**Comment by baSSiLL** [comment]
Hi

Using multiple threads for writing video frames and audio blocks is possible. There is a synchronization code where actual writing to an underlying stream happens. Whether organize your code multi- or single-threaded depends on your workflow.
SharpAvi does not work with video/audio sources - it only handles data that you feed it. How you get this data is beyond the scope of this lib.

If you reference the code example in the wiki article - that's just a simple "Hello world" level sample. A sample screencasting app in the codebase is a more elaborate example. There you can find multi-threading, async writing, capturing audio (using NAudio library) etc.

FYI, AVI specs do not state any explicit interleaving scheme for video and audio - the format even permits no actual interleaving, when for instance all video is written first followed by all audio. However, in practice many players tend to "like" when video and audio are interleaved more or less evenly - say 1 video frame then 1 audio block then 1 video frame then 1 audio block etc.

**Comment by AndersBillLinden** [comment]
Would it be a good idea to have only one thread for all the capturing taking screenshot after screenshot with a pause between every screenshot adapted to the desired framerate, but after each screenshot also check how much data there has arrived from the microphone and put that in the audio stream? Will the video playback assume that the sound is starting together with the first screenshot? How well will the images and the sound samples go in sync with each other? The method will consist of 1. take screenshot, 2. put in video stream 3. take data from the microphone 4. put in audio stream 5. compute the amount of time that should elapse before the next screenshot should be taken. 6. sleep that time 7. go back to 1?

**Comment by baSSiLL** [comment]
Yes, such approach is viable in case you can use "pull" model for obtaining video and audio data.
Yes, AVI format implies simultaneous start of all streams. How well they go in sync depends on whether actual rate of the data you write corresponds to what is set in a stream header. For instance, if you set 30 fps for video and actually write 25 frames per second while audio is written at the full rate then they will be out of sync during playback.

**Comment by AndersBillLinden** [comment]
What is "pull" model then? Video and audio will be fetched very differently because video will not fetch data that has automatically been filled up in an internal buffer like audio will. Maybe that is not related to the pull concept, so I´d better ask.

**Comment by baSSiLL** [comment]
Pull model references to workflow when data consumer asks data provider if data available, often on periodic basis. In contrast push model implies data provider notifies data consumer when data becomes available.
