### ISSUE TITLE
DivideByZeroException using Mpeg4VideoEncoderVcm with xVid

### ISSUE THREAD

**Issue by joserelloso** [baSSiLL/SharpAvi#13]
Hi Great library!!

I'm using this code to get an mp4 video, it works fine running on iisExpress,

        public static byte[] CreateMovie(List<string> frames)
        {
            var width = 320;
            var height = 240;
            var framRate = 20;
            var quality = 100;

            using (var ms = new MemoryStream())
            {
                var writer = new AviWriter(ms, true)
                {
                    FramesPerSecond = framRate,
                    EmitIndex1 = true
                };

                var codecs = Mpeg4VideoEncoderVcm.GetAvailableCodecs();

                log.Debug("System Available Codecs");
                foreach (var c in codecs)
                {
                    log.Debug(c.Codec);
                }

                FourCC selectedCodec = KnownFourCCs.Codecs.Xvid;

                log.Debug("Using Codec");
                log.Debug(selectedCodec.ToString());

                try
                {
                    var encoder = new Mpeg4VideoEncoderVcm(
                        width,
                        height,
                        framRate,
                        frames.Count,
                        quality,
                        selectedCodec);

                    var stream = writer.AddEncodingVideoStream(encoder, true, width, height);

                    foreach (var frame in frames)
                    {
                        byte[] arr = Convert.FromBase64String(frame);
                        var bm = ToBitmap(arr);
                        var rbm = ReduceBitmap(bm, width, height);

                        byte[] fr = BitmapToByteArray(rbm);

                        stream.WriteFrame(true, fr, 0, fr.Length);
                    }
                }
                catch (Exception ex)
                {
                    log.Debug("Video Creation Exception");
                    log.Debug(ex.ToString());
                }

                writer.Close();

                return ms.ToArray();
            }
        }

but when i deploy to my server the code trowhs the following exception

System.Reflection.TargetInvocationException:  
System.DivideByZeroException: Attempted to divide by zero.
   at SharpAvi.Codecs.VfwApi.ICSendMessage(IntPtr handle, Int32 message, BitmapInfoHeader& inHeader, BitmapInfoHeader& outHeader)
   at SharpAvi.Codecs.Mpeg4VideoEncoderVcm.StartCompression()

some clue about what may be happening?

thanks!! :)

**Comment by baSSiLL** [comment]
Do you run in 64 bits? I remember exactly this error when encoding with Xvid in 64 bits. The only MPEG-4 codec I've successfully used in 64 bits is x264vfw.

**Comment by joserelloso** [comment]
Hi baSSiLL, i'm running 32 bits

**Comment by baSSiLL** [comment]
Please check once more if you're running in 32 bits (value of **System.Environment.Is64BitProcess**). I've just checked the sample app with the [latest Xvid](https://www.xvid.com/download/) and it works OK in 32 bits but fails with DivideByZeroException in 64 bits.

**Comment by joserelloso** [comment]
Hi baSSiLL, i've changed it from Properties -> Build -> Platform Target
Where could i find this System.Environment.Is64BitProcess ?
Thanks!

**Comment by joserelloso** [comment]
Hi baSSiLL, i've solved! it was app pool config setting.
great library!! thanks!!
