### ISSUE TITLE
DLL is not signed

### ISSUE THREAD

**Issue by lanasat** [baSSiLL/SharpAvi#15]
I was wondering if there is a signed version for this DLL or not?

I get this warning when I use the current version which will not allow me to publish with it.
`warning CS8002: Referenced assembly 'SharpAvi, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

**Comment by baSSiLL** [comment]
Hi
No, there is no signed version so far, and is not planned currently.
As a workaround you can build DLL from the sources and sign it with your code signing cert if you have one or with self-issued cert which is suitable for some scenarios like running under Full Trust.
