### ISSUE TITLE
XVid Stats reader.

### ISSUE THREAD

**Issue by BaitForTheBuzzards** [baSSiLL/SharpAvi#16]
Thanks for a great project. Really brilliant code. I have a question about xvid. When I use xvid to create the video stream it launches a Status Application. Any idea how to get it to not launch the application?

thanks!!

**Comment by baSSiLL** [comment]
Hi @BaitForTheBuzzards 
AFAIK it can be disabled in encoder configuration. Look for **Encoder Config** shortcut in XVid folder in Start menu. In config dialog, click **Other options...** button in the bottom and then uncheck **Display encoding status** on **Encoder** tab.

**Comment by BaitForTheBuzzards** [comment]
Thanks!!!!!
