### ISSUE TITLE
Clarification on licensing of components

### ISSUE THREAD

**Issue by dbruning** [baSSiLL/SharpAvi#17]
Hi,

Thanks for this project! 

I can see that this project has a permissive license, but it's not clear whether there are any further licensing issues for components used by this library. For example, where did lameenc32.dll come from & what license does it have? 

Thanks, Darren.

**Comment by baSSiLL** [comment]
Hi @dbruning 

SharpAvi library itself does not include any 3d party dependencies or code parts.
However, it _can_ make use of certain 3d party components with their own licenses to implement some features. For instance, LAME MP3 encoder library or MPEG-4 video encoders like Xvid. Decision on whether to install/use those components with connection to SharpAvi is up to you.

**lameenc32.dll** is included with the sample app only as a demonstration.
