### ISSUE TITLE
MPEG-4 issue

### ISSUE THREAD

**Issue by Kartijno** [baSSiLL/SharpAvi#18]
Hi,

i tried your SharpAVI but using x264 codec it returns (your encoder constructor) that i dont have MPEG-4 compatible codec but getavailablecodec() return x264 . How i can work with this? Thanks
F

**Comment by baSSiLL** [comment]
Hi @Kartijno 
The problem may be with some parameters of encoding. For instance, specified frame resolution is not supported by the codec. What dimensions are you trying to use? It's usually safe to go with multiples of 8 for width and height with MPEG-4 codecs.

**Comment by Kartijno** [comment]
Hi Vasili!

I use fullhd size . 😒

Il giorno gio 2 ago 2018 alle 14:01 Vasili Maslov <notifications@github.com>
ha scritto:

**Comment by baSSiLL** [comment]
Then guessing... Did you try running both in 64 and 32 bits? Maybe you've only installed codec for one of the platforms.

**Comment by Kartijno** [comment]
I used codec 64 bit for 64 bit machine x264vfw64 that install both

Il giorno gio 2 ago 2018 alle 16:15 Vasili Maslov <notifications@github.com>
ha scritto:

**Comment by baSSiLL** [comment]
Looks like 64-bits only installer. Combined 64+32 bits installer does not end with "64", look at this one
https://sourceforge.net/projects/x264vfw/files/x264vfw/44_2851bm_44825/

However does you program run in 64 bits? There is a setting in .NET projects like _Prefer 32 bits_ which could be on.
