### ISSUE TITLE
Error from AddMpeg4VideoStream for any codec

### ISSUE THREAD

**Issue by riegaz** [baSSiLL/SharpAvi#19]
I get an error independent which encoder I chose. Even the MotionJpeg does through a "No compatible MPEG-4 encoder found" message. However `AddMotionJpegVideoStram` works.

`var vidStream = vidWriter.AddMpeg4VideoStream(1008, 1019, (double)30, quality: 70, codec: KnownFourCCs.Codecs.MotionJpeg);`

I installed x264 and xvid, both through errors as well.

I'm on Windows 10.

**Comment by baSSiLL** [comment]
Hi @riegaz 
**MotionJpeg** is not an MPEG-4 codec so it won't work with **AddMpeg4VideoStream**.
As for MPEG-4 codecs I suppose the error is due to unsupported frame size. MPEG-4 codecs usually require width and height to be multiples of 4 or 8.

**Comment by riegaz** [comment]
Thanks! I was not aware of the ratio. The error message was leading me in the wrong direction.
