### ISSUE TITLE
WPF Add ImageSource

### ISSUE THREAD

**Issue by Miro382** [baSSiLL/SharpAvi#20]
Hi,
How to write imagesource to stream?

I trying Imagesource to bytes but I get:
    "System.ArgumentException: 'Buffer size is not sufficient.'"

In documentation I read I need write DIB. How to convert ImageSource to Windows DIB?

```
//I convert canvas to Imagesource bytes
byte[] canvasdata = CanvasWriter.SaveCanvasToImgSimulate(canvas, (int)canvas.Width, (int)canvas.Height);

var writer = new AviWriter("test.avi")
{
    FramesPerSecond = 30,
    // Emitting AVI v1 index in addition to OpenDML index (AVI v2)
    // improves compatibility with some software, including 
    // standard Windows programs like Media Player and File Explorer
    EmitIndex1 = true
};

var stream  = writer.AddMotionJpegVideoStream((int)data.CanvasW, (int)data.CanvasH, 70);

stream.WriteFrame(true, canvasdata, 0, canvasdata.Length);

writer.Close();
```
Thanks

**Comment by baSSiLL** [comment]
Hi @Miro382 
If your **ImageSource** actually inherits from **BitmapSource** then you can use [CopyPixels](https://docs.microsoft.com/ru-ru/dotnet/api/system.windows.media.imaging.bitmapsource.copypixels) method to get image bytes. Probably using additionally **FormatConvertedBitmap** and/or **TransformedBitmap** to get data in proper format.
If it's not a **BitmapSource** then you can first render it to a **RenderTargetBitmap** and get its bitmap data.

**Comment by Miro382** [comment]
It works, Thanks
I used this function for other:

```
        private byte[] BitmapSourceToArray(BitmapSource bitmapSource)
        {
            // Stride = (width) x (bytes per pixel)
            int stride = (int)bitmapSource.PixelWidth * (bitmapSource.Format.BitsPerPixel / 8);
            byte[] pixels = new byte[(int)bitmapSource.PixelHeight * stride];

            bitmapSource.CopyPixels(pixels, stride, 0);

            return pixels;
        }
```
