### ISSUE TITLE
The recorded video is played back at 5x speed

### ISSUE THREAD

**Issue by anand1688** [baSSiLL/SharpAvi#23]

**Comment by baSSiLL** [comment]
Hi
At first sight looks like frame sequence you provide to SharpAvi has an actual frame rate lower than the value you've set for an AVI file. This usually happen when time needed to process a single frame being recorded from a live source (like camera or screencast) is more than 1/FPS.
Could you put more details about your problem? Are you talking about the sample screencast app or your own program? If the latter, what is it purpose, how the recording process is implemented?

**Comment by anand1688** [comment]
Hi 

I have used the same logic as the sample code.

I have modified it to capture just a particular application window.

Everything else is the same.If I record a video for 10 s the out put video length is  2s

**Comment by baSSiLL** [comment]
What frame rate do you set for a video? And what is an actual rate of screenshots you write to an output video stream? To get the latter, count how many frames have been written in total and divide that by recording time.

**Comment by anand1688** [comment]
Hi

Frame rate I have set at 10
FramesPerSecond=10
The frame interval to capture is deduced as 
var time_between_capture=TimeSpan.FromSeconds((1 / (double)writer.FramesPerSecond));

Also if I select any other codec than MotionJpeg, I get an vfw exception

**Comment by baSSiLL** [comment]
Check the number of frames that have been actually written to the stream - **AviVideoStream.FramesWritten** property. Is it close to 10 * <total seconds> or 2 * <total seconds>?

**Comment by baSSiLL** [comment]
As for codecs failure. Whether you run the program in 32 or 64 bits? The only MPEG-4 codec I've found working reliably in 64 bits is x264vfw. Of course, its 64-bit version should be installed.

**Comment by anand1688** [comment]
hi

I recorded for 20 s approx at FramePerSecond=10 the value is 31.

**Comment by baSSiLL** [comment]
So the actual frame rate is ~1.5 frames/second! When player opens an AVI file it plays those frames at 10 fps because hence the playback looks accelerated.
You need to find a reason why your capture pipeline does not keep up with target 10 fps. Measure which part of frame processing takes the most time - getting screenshot, writing to a stream, thread synchronization or image processing if you have any.

**Comment by anand1688** [comment]
Hi I found the issue,I was finding the window each time the capture was happenning

**Comment by baSSiLL** [comment]
Cool! Thanks for letting know.

**Comment by Dimolade** [comment]
Im having he Same Issue right now, FPS is 60 I recorded for 10 Seconds and Ouput is 4 seconds and frames are 289

**Comment by baSSiLL** [comment]
I believe a reason is the same: your recording process produces frames at much less rate than the specified 60 fps. So a resulting video looks accelerated when played back. Analyze your code to find performance issues.
