### ISSUE TITLE
Generated uncompressed videos are corrupt 1 out of 4 times

### ISSUE THREAD

**Issue by KoenT-IM** [baSSiLL/SharpAvi#25]
Hi Vasili,

I just encountered issues with uncompressed files generated by SharpAVI (last released version from NuGet).

SharpAVI will write uncompressed AVI files, but then when you open them, Windows Media Player will fail to open them and show an error dialog (other players such as VLC or avidemux will not play them correctly either). This is on Windows 10 Pro 64-bit (latest updates).

After some more testing, the issue seems to be that it only works properly if the width of the images that are added to the stream are a multiple of 4. So the .avi files will only play properly in 1 out of 4 cases (if you use different sizes each time). When I use the MJPEG encoder, all generated videos work fine.

I have attached a very simple self-contained Visual Studio 2015 project that reproduces this issue consistently: [TestSharpAVI.zip](https://github.com/baSSiLL/SharpAvi/files/3530234/TestSharpAVI.zip)

If you could find a moment to look into this issue, that would be great.

Best,
Koen

**Comment by baSSiLL** [comment]
Hi @KoenT-IM 
Thanks for reporting. Indeed, I didn't consider 4-byte alignment for scan lines when implemented `UncompressedVideoEncoder`. I will make a fix soon.

**Comment by baSSiLL** [comment]
@KoenT-IM Please check whether the issue is fixed in the latest sources.

**Comment by KoenT-IM** [comment]
Thanks for the fast reaction! I'll try to find a moment to test this soon!

**Comment by KoenT-IM** [comment]
Hi again Vasili!
I've just rebuilt the library from the latest code you just pushed, and tested in the TestSharpAVI project I had attached and also in our application: I can confirm that this fixes the issue.
Will you release a new NuGet package?
Thanks a lot for the fast and effective reaction!

**Comment by baSSiLL** [comment]
Yes, I'll release an updated package in a few days.

**Comment by KoenT-IM** [comment]
Great, thanks!

**Comment by baSSiLL** [comment]
@KoenT-IM I've published the updated package.

**Comment by KoenT-IM** [comment]
OK, thanks!
I'll close the ticket now ;-)
