### ISSUE TITLE
Installed codecs not recognized

### ISSUE THREAD

**Issue by Steffx115** [baSSiLL/SharpAvi#26]
I am trying to use the Mpeg4 video stream, with mp43 encoding (which is installed on my computer), but GetAvailableCodecs returns only x264 (and when i use this all recordings just are just black, with a size of 5 KB, which cant be the correct filesize).  Maybe i installed the wrong encoders, could you provide us the link to the encoders which were used for testing?

**Comment by baSSiLL** [comment]
Hi
Microsoft MPEG4 encoders are provided as 32-bit binaries only, so if your process runs in 64 bits then they are not available.
For x264, did you check **Zero Latency** option in codec settings?
