### ISSUE TITLE
how can i use "X264" or "MPG4" encoder

### ISSUE THREAD

**Issue by singba** [baSSiLL/SharpAvi#29]
Mpeg4VideoEncoderVcm.GetAvailableCodecs()  always empty
{SharpAvi.Codecs.CodecInfo[0]}

**Comment by baSSiLL** [comment]
Either you have no compatible codecs installed or you run the program as 64 bit process while installed codec is 32 bit.
Here are links to some codecs
- X264 https://sourceforge.net/projects/x264vfw/ (there are separate installers for 32 bit and 64 bit versions)
- Xvid https://www.xvid.com/download/

**Comment by dorathoto** [comment]
another option, not the most effective, just the most practical. is to install a set of codecs, the good part is that you will get a very good player (MPC-HC)
https://codecguide.com/download_kl.htm
