### ISSUE TITLE
AviWrite Close Function Trouble ( Fx35 Version )

### ISSUE THREAD

**Issue by BBUBBA** [baSSiLL/SharpAvi#31]
When i Try Call AviWriter Close Function (Not Stream, It's File Name)
Stream is Not Dead... (Because closeWirter is False)

        public AviWriter(string fileName)
        {
            Contract.Requires(!string.IsNullOrEmpty(fileName));

            #if !FX45

            streamsRO = new ReadOnlyCollection<IAviStream>(streamsList);
            closeWriter = true;  <---- #########Plase Add this.#########

            #endif

            var fileStream = new FileStream(fileName, FileMode.Create, FileAccess.Write, FileShare.None, 1024 * 1024);
            fileWriter = new BinaryWriter(fileStream);
        }

Thanks so much ^^ i Like this Project.

**Comment by baSSiLL** [comment]
Thanks for reporting! Looks like a bug. As a workaround you can open FileStream yourself and use a constructor with Stream parameter which handles leaveOpen parameter correctly.

**Comment by BBUBBA** [comment]
Thank about Reply ^^

One more FX35 Version Sample Project Bug

         void RecordScreen()
         {
                  ...
                  ...
                  ...
            if (!isFirstFrame)
            {
            #if FX45
                videoWriteTask.Wait();
            #else
                if (!videoWriteResult.IsCompleted)         // <---------- Add this
                    videoStream.EndWriteFrame(videoWriteResult);
            #endif
            }
                  ...
                  ...
                  ...
         }
