### ISSUE TITLE
x264vfw Record Error..

### ISSUE THREAD

**Issue by BBUBBA** [baSSiLL/SharpAvi#32]
When I Try Make VideoStream...

Sometime Error.... ( maybe case by case about Record Size. )

( I think When Try record Small Bitmap... CreateVideoStream Error... | Just x264vfw Codec )

       public static CodecInfo[] GetAvailableCodecs()
        {
            var result = new List<CodecInfo>();

            //var inBitmapInfo = CreateBitmapInfo(8, 8, 32, KnownFourCCs.Codecs.Uncompressed);   <--- Okay
            var inBitmapInfo = CreateBitmapInfo(385, 160, 32, KnownFourCCs.Codecs.Uncompressed);   <--- Error
            inBitmapInfo.ImageSize = (uint)4;

            foreach (var codec in DefaultCodecPreference)
            {
                //var outBitmapInfo = CreateBitmapInfo(8, 8, 24, codec);   <--- Okay
                var outBitmapInfo = CreateBitmapInfo(385, 160, 24, codec);    <---- Error
                VfwApi.CompressorInfo compressorInfo;
                var compressorHandle = GetCompressor(inBitmapInfo, outBitmapInfo, out compressorInfo);
                if (compressorHandle != IntPtr.Zero)
                {
                    VfwApi.ICClose(compressorHandle);
                    result.Add(new CodecInfo(codec, compressorInfo.Description));
                }
            }

            return result.ToArray();
        }

    public class CodecInfo
    {
        public CodecInfo(FourCC codec, string name);

        public FourCC Codec { get; }
        public string Name { get; }
    }

Size = 8,8 Okay !
Size = 385, 160 Error !
Size = 1920, 1080 Okay !

Size = Something ( Sometime Okay, Sometime Error Because Record Size )

Thank you So much ^^

**Comment by BBUBBA** [comment]
I Found solve solution.

          if (Width % 2 == 1) Width--;
          if (Height % 2 == 1) Height--;

I don't know why.... But Work..

**Comment by baSSiLL** [comment]
Some codecs put limitations on frame dimensions. Usually that width and height are multiples of some power of 2 (2/4/8).
