### ISSUE TITLE
Continuous recording, writing out to multiple files

### ISSUE THREAD

**Issue by alantan** [baSSiLL/SharpAvi#37]
I am thinking of creating a method in AviWriter that would allow closing the current .avi file and creating a new one, continuing to write the frames and audio to the new one. This would allow continuous recording, by adding a new N-minute file, and deleting the oldest N-minute file.  Before I start on this, do you think this approach would work well?  Are there any gotchas that I need to look out for or do you think an alternative approach would be better?
PS: Many thanks for this library, it's does what it claims really well. :-)

**Comment by baSSiLL** [comment]
IMO this should be made on top of AviWriter, and not supported by it directly.
