### ISSUE TITLE
Issue with example

### ISSUE THREAD

**Issue by computerman46** [baSSiLL/SharpAvi#44]
Examples have this line of code:
`var frameData = new byte[stream.Width * stream.Height * 4](stream.Width-_-stream.Height-_-4);`
but this code has no sense, it's object not a method, and `-_-` just a ascii smile, not a code, 
and if i just load bmp file as byte array, or i load it in memory stream and convert to byte array, 
on output i have just black screen.

**Comment by baSSiLL** [comment]
Thanks for noticing. Apparently the part in parentheses should be removed.
Looks to me like an URL template in markdown, probably appeared when transferred docs from CodePlex.

> if i just load bmp file as byte array, or i load it in memory stream and convert to byte array,
on output i have just black screen

Please post a code which you try to run.
