### ISSUE TITLE
Mpeg4VideoEncoderVcm.GetAvailableCodecs returns an empty array

### ISSUE THREAD

**Issue by TomArrow** [baSSiLL/SharpAvi#46]
I definitely have a bunch of VfW codecs installed but this gives me an empty array. x64 mode. VirtualDub x64 shows them all. Specifically, I would like to use MagicYUV.

**Comment by baSSiLL** [comment]
Hi
If you are talking about `Mpeg4VideoEncoderVcm.GetAvailableCodecs` then it only returns the ones available from the list it explicitly supports - MS MPEG4, XVid, DivX, X.264.

**Comment by TomArrow** [comment]
Ah, gotcha. Do you know a convenient way to query all available VfW codecs that are installed on the system?

**Comment by baSSiLL** [comment]
None ready-made.
If you want to use a specific codec, determine its FOURCC and pass it in the `codecPreference` parameter to 'Mpeg4VideoEncoderVcm'. Although I'm not sure 'Mpeg4VideoEncoderVcm' will work correctly with non-MPEG4 codecs (and MagicYUV you mention is non-MPEG4).
