### ISSUE TITLE
AviWriter does not close file 

### ISSUE THREAD

**Issue by dierberg** [baSSiLL/SharpAvi#47]
After a 
using (AviWriter writer = new AviWriter(fn))
{ 
    ... 
 writer.close();
}
it is not possible to access the file until process ist terminated. 

var s = new BufferedStream(File.OpenRead(fn), 1000000); 

throws an IOException. Also opening with Mediaplayer does not work.

**Comment by baSSiLL** [comment]
Hi
There is probably a bug with this constructor. You can use one taking a `Stream` as a workaround. It should close the stream properly (unless `leaveOpen: true` is specified), and you can close the stream on your own.

**Comment by dierberg** [comment]
I have added a fileWriter.Dispose() in AviWriter.Close() in my fork and this works as expected.

**Comment by baSSiLL** [comment]
Fixed by changing the default value.
