### ISSUE TITLE
Trouble with x264vfw

### ISSUE THREAD

**Issue by DenisenkoNS** [baSSiLL/SharpAvi#49]
x264vfw [warning]: Few frames probably would be lost. Ways to fix this:
x264vfw [warning]:  - if you use VirtualDub or its fork than you can enable 'VirtualDub Hack' option
x264vfw [warning]:  - you can enable 'File' output mode
x264vfw [warning]:  - you can enable 'Zero Latency' option
When i trying record screen with x264vfw encoder i got this, and black screen on 1-5s of video, you recommended to check Zero Latency  option, but i cant understand how, can you help pls?

**Comment by baSSiLL** [comment]
x264vfw installs a configuration app. Run it and check **Zero Latency** there. The setting is persistent and should be applied when x264 is used with SharpAvi.
![image](https://user-images.githubusercontent.com/1926484/149514246-2e3306a8-37ac-43c9-9129-1d06143bb40a.png)

**Comment by DenisenkoNS** [comment]
Thank you very match
