### ISSUE TITLE
AVI Wrapped to the right slightly

### ISSUE THREAD

**Issue by stevehjohn** [baSSiLL/SharpAvi#51]
Hi,

Thanks for the super useful library.

Unfortunately, I've found an issue in my usage of it. The AVI seems to shift the source bitmaps a few pixels to the right, with the right edge wrapping around to the left.

It is probably best explained with an image, see below.

![image](https://user-images.githubusercontent.com/4673357/159255155-cf462caf-2770-4059-b445-f36f751ad9f7.png)

Thanks,

Steve.

**Comment by baSSiLL** [comment]
Hi
It's not apparent from the image how it should look like normally. But as soon as vertical lines don't get inclined I suppose there's a constant shift in bitmap data. Probably, a wrong start of bitmap data is specified.
What is the source of frames? How do you pass frames to SharpAvi? Which encoder do you use?

**Comment by stevehjohn** [comment]
Hi,

Thanks for responding. The bitmaps are captured from the screen with the following code:

https://github.com/stevehjohn/AoC/blob/a4bbe7321ff5b22fae0c65c936288eed8ad9dc00/AoC.Visualisations/Infrastructure/VisualisationBase.cs#L84

You can see the video here: https://youtu.be/eAzu7xScquA?t=83
From about 1:20 there is a stream of water that should be at the very right hand edge of the frame, but as you can see, it is wrapped around to the left.

Thanks,

Steve.

**Comment by baSSiLL** [comment]
I see. You should not save a bitmap to the BMP format before passing to SharpAvi. This way the array you pass to `WriteFrame` contains not only raw pixel data but also a few excess bytes in the beginning coming from the BMP header. Hence the shift in pixels.
Take a look to a similar code in the sample app.
https://github.com/baSSiLL/SharpAvi/blob/02b1447c5a79db9cf0ee12cbbb3bbba3dc86cb82/Sample/Recorder.cs#L228
You just call `LockBits' to get a pointer to a `Bitmap`'s pixel data. And then you can either copy it to an array, a `MemoryStream` or other managed memory. Or use unsafe code and create a `Span` directly from the pointer which you can then pass to `WriteFrame`.
```cs
var bits = bitmap.LockBits(new Rectangle(0, 0, bitmap.Width, bitmap.Height), ImageLockMode.ReadOnly, PixelFormat.Format24bppRgb);
var span = new Span<byte>(bits.Scan0.ToPointer(), bits.Stride * bits.Height);
videoStream.WriteFrame(true, span);
bitmap.UnlockBits(bits);
```

**Comment by baSSiLL** [comment]
You use an uncompressed video stream without an encoder, it expects pixel data in the bottom-up direction. It worked with the BMP format because it also stores pixels in the bottom-up direction. While the `Bitmap` class stores its data in the top-down direction.
You can turn to `UncompressedVideoEncoder` which expects top-down data and performs the necessary vertical flipping under the hood. Note that you'll also need to change the bitmap format to `PixelFormat.Format32bppRgb` as all encoders in SharpAvi expect pixel data in this format.

**Comment by stevehjohn** [comment]
Perfect, that all works now.

Thank-you for your help with this issue. I presume my original issue was caused by header information that is added when saving a bitmap?

Thanks,

Steve.

**Comment by baSSiLL** [comment]
> I presume my original issue was caused by header information that is added when saving a bitmap?
Correct

**Comment by stevehjohn** [comment]
Cool.

Once again, thanks for your help with this!

Steve.

**Comment by stevehjohn** [comment]
Appreciate your help, gave you a shout out here: https://www.outsidecontextproblem.com/threading.html

Cheers,

Steve.
