### ISSUE TITLE
SharpAvi 3.0.1: 'KnownFourCCs', 'AddUncompressedVideoStream', and 'AddMotionJpegVideoStream' Not Recognized in Visual Studio C#

### ISSUE THREAD

**Issue by aarif313** [baSSiLL/SharpAvi#69]
Environment:

SharpAvi Version: 3.0.1
IDE: Visual Studio
Language: C#
Description:
When attempting to use the latest version of SharpAvi (3.0.1) in a C# project within Visual Studio, the following code results in errors indicating that certain methods and types do not exist:

public IAviVideoStream CreateVideoStream(AviWriter writer)
{
    if (Codec == KnownFourCCs.Codecs.Uncompressed)
        return writer.AddUncompressedVideoStream(Width, Height);
    else if (Codec == KnownFourCCs.Codecs.MotionJpeg)
        return writer.AddMotionJpegVideoStream(Width, Height, Quality);
    else
    {
        return writer.AddMpeg4VideoStream(Width, Height, (double)writer.FramesPerSecond,
            quality: Quality,
            codec: Codec,
            forceSingleThreadedAccess: true);
    }
}

**Comment by baSSiLL** [comment]
Yep, there were breaking changed between v2 and v3. 
* `KnownFourCCs` was made internal and FourCCs for codecs have been moved to a new `CodecIds` class.
* `AddMotionJpegVideoStream` was replaced with two `AddMJpegWpfVideoStream` (Windows only). And `AddMJpegImageSharpVideoStream` (cross-platform) was added in a separate package **SharpAvi.ImageSharp**.
* AddUncompressedVideoStream is still there. Probably your code is missing `using SharpAvi.Codecs;`.

**Comment by aarif313** [comment]
Thanks, @baSSiLL , for your response.

My code is now working with the changes you suggested.

Regarding the last point you mentioned, "AddUncompressedVideoStream is still there. Probably your code is missing using SharpAvi.Codecs;," I wanted to clarify that "AddUncompressedVideoStream" is not available in my current setup(SharpAvi V3.0.1). Instead, I used "AddMpeg4VcmVideoStream." Could you kindly check this again? For your information, I have already included "using SharpAvi.Codecs;" in my code.

Thank you again for your help.

**Comment by aarif313** [comment]
Thanks, @baSSiLL, for your response.

My code is now working with the changes you suggested.

Additionally, I wanted to inform you that "AddMpeg4VideoStream" is also not available in my current setup(SharpAVI V3.0.1). Instead, I used "AddMpeg4VcmVideoStream." Could you kindly confirm if this is fine? 

Thank you again for your help.

**Comment by baSSiLL** [comment]
Yep, it's the same implementation. Just renamed for clarity that it is based on the Windows VCM.
