### ISSUE TITLE
Append new video frames and audio samples

### ISSUE THREAD

**Issue by LeeeJoe** [baSSiLL/SharpAvi#7]
How can I append new video frames and audio samples to my avi file (with the same options) ?

**Comment by baSSiLL** [comment]
Appending to existing files is not supported. SharpAvi does not include any means for reading AVI files that is obviously required for appending.

**Comment by LeeeJoe** [comment]
I understood. Although it would be great. Maybe there are plans in the near future? How else can I contact you?
